
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: 1


services:
  backend:
    build: ./backend
    entrypoint:
      - "/project/entrypoint.sh"
    volumes:
      - "./backend:/project"
    depends_on:
      - db
    env_file:
      - ${APP_ENV_FILE}
    ports:
      - ${APP_PORT}:8000
    <<: *logging

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped
    <<: *logging

  db:
    image: postgres:17
    restart: always

    volumes:
      - .docker_volumes/postgres_data:/var/lib/postgresql/data
    env_file:
      - ${DB_ENV_FILE}
    <<: *logging


  test_db:
    image: postgres:16-alpine
    container_name: test_taskmanager_db
    environment:
      POSTGRES_DB: test_taskmanager
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - test_db

volumes:
  test_db_data: